spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 5GB
  security:
    enabled: false
    user:
      name: admin
      roles: admin
      password: admin123
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  application:
    name: Windows服务管理
# 日志相关的配置，还有些问题，后续要改成xml的方式来配置.
logging:
  file:
    name: logs/windows-manager.log
  level:
    root: info
    org:
      apache: error
      springframework: error
server:
  port: 1111
app:
  cmd-start-service: net {} "{}"
  cmd-list-service: wmic service get Name,DisplayName,Description,PathName,StartMode,State,StartName /format:list
  cmd-list-service-where: wmic service where "{}" get Name,DisplayName,Description,PathName,StartMode,State,StartName /format:list

project:
  version: @project.version@
